"""phase 1 tables

Revision ID: da1ee61d2e18
Revises: 
Create Date: 2026-09-21 13:13:44.218426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da1ee61d2e18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cq_email'))
        batch_op.drop_index(batch_op.f('idx_cq_status_created'))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_items_active'))
        batch_op.drop_index(batch_op.f('idx_items_cat_sub'))

    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_subcat_category'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('failed_attempts',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('idx_users_type_active'))
        batch_op.drop_index(batch_op.f('uq_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('uq_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('idx_users_type_active'), ['user_type', 'is_active'], unique=False)
        batch_op.alter_column('failed_attempts',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=36),
               existing_nullable=False)

    with op.batch_alter_table('subcategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_subcat_category'), ['category_id', 'is_active'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_items_cat_sub'), ['category_id', 'subcategory_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_items_active'), ['is_active'], unique=False)

    with op.batch_alter_table('contact_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cq_status_created'), ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_cq_email'), ['email'], unique=False)

    # ### end Alembic commands ###
